### ISSUE TITLE
Separating imports from shebang

### ISSUE THREAD

**Issue by jtrakk** [asottile/reorder_python_imports#81] opened 2019-06-16 10:27 UTC
Looks like `black` is ok with 0, 1, or 2 blank lines between the shebang and the first import. But `reorder_python_imports` removes those lines. For example,

```python
#!/usr/bin/env python3


import typing as t

import attr

print("hello")

```

becomes

```python
#!/usr/bin/env python3
import typing as t

import attr

print("hello")
```

I'd like to keep those separating lines.

---
reorder-python-imports==1.5.0
python3.6

**Comment by asottile** [comment] 2019-06-16 14:23
Duplicate of #66

**Closed by asottile** 2019-06-16 14:23 UTC

**Comment by jtrakk** [comment] 2019-06-16 18:03
Ah sorry, I missed that.

**Comment by asottile** [comment] 2019-06-16 18:10
no problem! thanks for the issue 🎉
