### ISSUE TITLE
issue due to setuptools

### ISSUE THREAD

**Issue by beliaev-maksim** [asottile/reorder_python_imports#210] opened 2021-12-31 10:27 UTC
Just want to make it documented in case somebody faces the same issue due to the bug in `virtualenv`

`reorder-python-imports` fails with 
```bash
 Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repoizu8jol0/py_env-python3.10/bin/reorder-python-imports", line 8, in <module>
    sys.exit(main())
  File "/home/runner/.cache/pre-commit/repoizu8jol0/py_env-python3.10/lib/python3.10/site-packages/reorder_python_imports.py", line 907, in main
    retv |= _fix_file(filename, args)
  File "/home/runner/.cache/pre-commit/repoizu8jol0/py_env-python3.10/lib/python3.10/site-packages/reorder_python_imports.py", line 475, in _fix_file
    new_contents = fix_file_contents(
  File "/home/runner/.cache/pre-commit/repoizu8jol0/py_env-python3.10/lib/python3.10/site-packages/reorder_python_imports.py", line 456, in fix_file_contents
    partitioned = step(partitioned)
  File "/home/runner/.cache/pre-commit/repoizu8jol0/py_env-python3.10/lib/python3.10/site-packages/reorder_python_imports.py", line 366, in apply_import_sorting
    sorted_blocks = sort(import_obj_to_partition.keys(), **sort_kwargs)
  File "/home/runner/.cache/pre-commit/repoizu8jol0/py_env-python3.10/lib/python3.10/site-packages/aspy/refactor_imports/sort.py", line 96, in sort
    imports_partitioned[classify_func(import_obj)].append(import_obj)
  File "/home/runner/.cache/pre-commit/repoizu8jol0/py_env-python3.10/lib/python3.10/site-packages/aspy/refactor_imports/sort.py", line 73, in classify_func
    return classify_import(obj.import_statement.module, **kwargs)
  File "/home/runner/.cache/pre-commit/repoizu8jol0/py_env-python3.10/lib/python3.10/site-packages/aspy/refactor_imports/classify.py", line 138, in classify_import
    found, module_path, is_builtin = _get_module_info(
  File "/home/runner/.cache/pre-commit/repoizu8jol0/py_env-python3.10/lib/python3.10/site-packages/aspy/refactor_imports/classify.py", line 103, in _get_module_info
    assert spec.submodule_search_locations is not None
AssertionError
```

solution will be to update CI to force downgrade virtualenv:
```yaml
name: pre-commit

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

# Install venv to avoid issues https://github.com/pre-commit/action/issues/135
    - name: Install virtualenv
      run: |
        python -m pip install -U virtualenv==20.10.0
    - uses: pre-commit/action@v2.0.3
```

**Comment by asottile** [comment] 2021-12-31 16:58
can you provide a reproduction?  `reorder-python-imports` is working fine for me on latest virtualenv and I suspect there's something else going on

**Comment by asottile** [comment] 2021-12-31 20:59
looks like a bug in setuptools -- the proper workaround should be `SETUPTOOLS_USE_DISTUTILS=stdlib` -- the virtualenv workaround will stop working in a few weeks because of periodic update

**Comment by beliaev-maksim** [comment] 2022-01-03 19:57
Hi @asottile 
sorry for delay, you can play in my repo
https://github.com/beliaev-maksim/repro/pull/1

**Comment by beliaev-maksim** [comment] 2022-01-05 13:09
> the proper workaround should be `SETUPTOOLS_USE_DISTUTILS=stdlib`

I confirm that this also solves the issue

**Comment by AntoineD** [comment] 2022-01-05 21:27
@asottile Is there a way to use the workaround when reorder_python_imports is called by pre-commit without having to set the env variable in the context calling pre-commit?

**Comment by asottile** [comment] 2022-01-05 21:29
there's a bunch of choices:

1. override the `entry` to set the variable: `entry: env SETUPTOOLS_USE_DISTUTILS=stdlib reorder-python-imports1
2. since it's runtime and not installtime you could force an older setuptools: `additional_dependencies: [setuptools<60]

**Comment by asottile** [comment] 2022-01-08 19:47
this should be fixed in setuptools 60.5.0 !

**Closed by asottile** 2022-01-08 19:47 UTC

**Comment by beliaev-maksim** [comment] 2022-01-10 08:37
setuptools 60.5.0 is out.
I ran a pipeline as usual and it is working perfectly

@asottile 
thanks!

**Comment by davidism** [comment] 2022-01-13 21:18
In order to get the latest setuptools in pre-commit's reorder_python_imports env, I had to do the following:

```
$ virtualenv --upgrade-embed-wheels
$ pre-commit clean
$ pre-commit run
```

If I only did `pre-commit clean`, the new env it created would still have the old setuptools, it wasn't updating that automatically.
