### ISSUE TITLE
Recursive flag

### ISSUE THREAD

**Issue by Adwaith-Rajesh** [asottile/reorder_python_imports#175] opened 2021-06-08 09:23 UTC
A new flag `-r` in order to recursively find python file in a directory and its subdirectory to reorder the imports.

**Comment by MarcoGorelli** [comment] 2021-06-08 11:04
Hi @Adwaith-Rajesh - duplicate of https://github.com/asottile/pyupgrade/issues/339, https://github.com/asottile/pyupgrade/issues/150, and https://github.com/asottile/pyupgrade/issues/46 ? (different repo, but same kind of tool, so I think you can anticipate the same response)

**Closed** 2021-06-08 13:08 UTC

**Comment by gareth-leake** [comment] 2022-04-28 18:15
Just came across this -- really appreciate you including this, and making it so seamless!

**Comment by Floskinner** [comment] 2023-11-09 08:55
As a workaround you can do it like this:
```bash
find . -name *.py -type f | xargs reorder-python-imports
```

- `find . -name *.py -type f ` -> find all files in this directory and sub-directories with the name `*.py` and type file
- `xargs reorder-python-imports` -> places the found path at the end of this line and executes it
